"""Invoke the pinned maintained generators; compare or publish their output bytes."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import uuid

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from tools.contracts.registry_support import registries, select_registry, verify_historical_artifacts, verify_local_schema_references

CONTRACTS = ROOT / "contracts"
SCHEMA = CONTRACTS / "schemas" / "1.0.0" / "core.schema.json"
OUTPUT = CONTRACTS / "generated" / "1.0.0"
WORK = ROOT / ".intent-to-impact" / "spikes" / "FND-01-01"
RISK_WORK = ROOT / ".intent-to-impact" / "spikes" / "FND-01-03"
DESIGN_WORK = ROOT / ".intent-to-impact" / "spikes" / "FND-01-02"
NSP_WORK = ROOT / ".intent-to-impact" / "spikes" / "FND-01-03" / "LOCAL-09"
REGISTRY = json.loads((CONTRACTS / "registry" / "1.0.0.json").read_text(encoding="utf-8"))
ARTIFACTS = ("python/core.py", "typescript/core.d.ts")


def verify_toolchain() -> None:
    for line in (CONTRACTS / "requirements.lock.txt").read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        name, expected = line.split("==")
        actual = importlib.metadata.version(name)
        if actual != expected:
            raise RuntimeError(f"{name}: installed {actual}; locked {expected}")
    manifest = json.loads((CONTRACTS / "package.json").read_text(encoding="utf-8"))
    lock = json.loads((CONTRACTS / "package-lock.json").read_text(encoding="utf-8"))
    for name, expected in manifest["devDependencies"].items():
        installed = CONTRACTS / "node_modules" / name / "package.json"
        actual = json.loads(installed.read_text(encoding="utf-8"))["version"]
        locked = lock["packages"][f"node_modules/{name}"]["version"]
        if actual != expected or locked != expected:
            raise RuntimeError(f"{name}: installed {actual}; requested {expected}; locked {locked}")
    for location, package in lock["packages"].items():
        if not location:
            continue
        installed = CONTRACTS / location / "package.json"
        if json.loads(installed.read_text(encoding="utf-8"))["version"] != package["version"]:
            raise RuntimeError(f"Installed dependency differs from lock: {location}")


def generate(destination: Path, check: bool, bundle: str = "core", *, schema_version="1.0.0") -> bool:
    registry = select_registry(schema_version)
    verify_historical_artifacts(registry)
    published_output = CONTRACTS / "generated" / schema_version
    destination = destination.resolve()
    if destination != published_output.resolve() and not any(
        destination.is_relative_to(work.resolve()) for work in (WORK, RISK_WORK, DESIGN_WORK, NSP_WORK)
    ):
        raise ValueError("Output must be the versioned generated directory or this task's spike directory")
    verify_toolchain()
    bundles = [item for item in registry["bundles"] if bundle == "all" or item["name"] == bundle]
    if not bundles:
        raise ValueError(f"Unknown schema bundle: {bundle}")
    work = NSP_WORK if schema_version == "2.0.0" else WORK if bundle == "core" else RISK_WORK if bundle in {"scenario", "risk", "projections"} else DESIGN_WORK
    scratch = work / f"generation-{uuid.uuid4().hex}"
    scratch.mkdir(parents=True)
    env = {**os.environ, "PYTHONUTF8": "1", "PYTHONDONTWRITEBYTECODE": "1"}
    try:
        generated = {}
        for item in bundles:
            schema = CONTRACTS / item["schema"]
            if schema_version == "2.0.0":
                verify_local_schema_references(schema)
            python_output = scratch / f"{item['name']}.py"
            typescript_output = scratch / f"{item['name']}.d.ts"
            arguments = [
                sys.executable, "-m", "datamodel_code_generator",
                "--input", str(schema), "--input-file-type", "jsonschema",
                "--output", str(python_output),
                "--output-model-type", "typing.TypedDict",
                "--target-python-version", "3.11",
                "--no-use-closed-typed-dict",
                "--enum-field-as-literal", "all",
                "--no-use-standard-primitive-types",
                "--disable-timestamp",
                "--formatters", "black", "isort",
                "--custom-file-header",
                "# GENERATED by datamodel-code-generator. DO NOT EDIT.\n"
                f"# Source: contracts/{item['schema']}\n"
                "# Regenerate: tools/contracts/generate.py\n"
                "# JSON Schema validation, not these structural types, is authoritative.",
            ]
            if schema_version == "2.0.0":
                # The maintained CLI classifies ancestor local files as external.
                # Every transitive ref was confined to registered local schemas above.
                arguments.extend(["--strict-refs", "--allow-remote-refs"])
            elif item["name"] != "core":
                arguments.extend(["--strict-refs", "--no-allow-remote-refs"])
            subprocess.run(arguments, cwd=CONTRACTS, env=env, check=True)
            subprocess.run(
                [
                    "node", str(ROOT / "tools" / "contracts" / "generate_types.cjs"),
                    str(schema), str(typescript_output),
                ],
                cwd=CONTRACTS, env=env, check=True,
            )
            generated[item["python"]] = python_output.read_text(encoding="utf-8").encode("utf-8")
            generated[item["typescript"]] = typescript_output.read_text(encoding="utf-8").encode("utf-8")
        for name, data in generated.items():
            frozen = {**registry.get("frozenCoreFiles", {}), **registry.get("frozenRiskFiles", {})}.get(
                f"contracts/generated/{schema_version}/{name}"
            )
            if frozen and hashlib.sha256(data).hexdigest() != frozen:
                raise RuntimeError(f"Generator changed frozen output: {name}")
        if check:
            expected_paths = {destination / name for name in generated}
            unselected_paths = {
                destination / item[language]
                for item in registry["bundles"] if item not in bundles
                for language in ("python", "typescript")
            }
            actual_paths = {
                p for p in destination.rglob("*")
                if p.is_file() and "__pycache__" not in p.parts and p not in unselected_paths
            }
            drift = [str(p.relative_to(destination)) for p in actual_paths - expected_paths]
            for name, data in generated.items():
                target = destination / name
                if not target.is_file() or target.read_bytes() != data:
                    drift.append(name)
            if drift:
                print("Generated type drift: " + ", ".join(sorted(drift)), file=sys.stderr)
                return False
            print(f"Generated types match pinned generators ({len(generated)} artifacts, byte-for-byte).")
        else:
            for name, data in generated.items():
                target = destination / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
            print(f"Generated {len(generated)} artifacts in {destination}")
        return True
    finally:
        shutil.rmtree(scratch)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Regenerate and compare; never modify target files")
    parser.add_argument("--output-dir", type=Path, help="Optional isolated task-local output")
    parser.add_argument("--schema-version", default="1.0.0", help="Explicit published schema version; legacy default never changes")
    parser.add_argument(
        "--bundle", default="core",
        choices=["all", *sorted({item["name"] for registry in registries().values() for item in registry["bundles"]})],
        help="Default preserves the accepted core-only command; use all to check every registered bundle",
    )
    args = parser.parse_args()
    try:
        output = args.output_dir or CONTRACTS / "generated" / args.schema_version
        return 0 if generate(output, args.check, args.bundle, schema_version=args.schema_version) else 1
    except (
        OSError, ValueError, RuntimeError, importlib.metadata.PackageNotFoundError,
        subprocess.CalledProcessError,
    ) as error:
        print(f"Contract generation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
