"use strict";

const fs = require("node:fs/promises");
const path = require("node:path");
const contracts = path.resolve(__dirname, "..", "..", "contracts");
const { compileFromFile } = require(
  path.join(contracts, "node_modules", "json-schema-to-typescript"),
);

async function main() {
  const [schema, output] = process.argv.slice(2);
  if (!schema || !output) {
    throw new Error("Usage: node generate_types.cjs <schema> <output>");
  }
  const generated = await compileFromFile(schema, {
    bannerComment:
      "/* GENERATED by json-schema-to-typescript. DO NOT EDIT.\n" +
      ` * Source: contracts/${path.relative(contracts, schema).split(path.sep).join("/")}\n` +
      " * Regenerate: tools/contracts/generate.py\n" +
      " * JSON Schema validation, not these structural types, is authoritative.\n */",
    additionalProperties: false,
    declareExternallyReferenced: true,
    $refOptions: { resolve: { http: false } },
    unreachableDefinitions: true,
    unknownAny: true,
    strictIndexSignatures: true,
    style: {
      semi: true,
      singleQuote: false,
      trailingComma: "all",
      printWidth: 100,
      endOfLine: "lf",
    },
  });
  await fs.writeFile(output, generated, "utf8");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
