"""Authored, example-only judge simulation. No credentials, SDKs or network calls.

example-input.json is generated by Generate-Example.mjs from the frontend's
EXAMPLE_PROMPT / EXAMPLE_DOCUMENTS. Changes to user instructions select only the
next scripted revision; this is deliberately not natural-language inference.
"""

import copy
import re
import secrets
from pathlib import Path

from .validation import StudioFailure, strict_json

WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
REPOSITORY_ROOT = WORKSPACE_ROOT.parent if WORKSPACE_ROOT.name == "intent-to-impact-studio" else WORKSPACE_ROOT
EXAMPLE_PATH = REPOSITORY_ROOT / "aca" / "example-input.json"
MODEL = "judge-simulator"


class JudgeSimulator:
    origin = "simulated"

    def __init__(self):
        try:
            example = strict_json(EXAMPLE_PATH.read_bytes())
            self.prompt = example["prompt"]
            self.documents = self._documents(example["documents"])
            if not isinstance(self.prompt, str) or not self.prompt or not self.documents:
                raise ValueError
        except (OSError, KeyError, TypeError, ValueError, StudioFailure):
            raise RuntimeError("Generate the canonical judge example input before enabling simulation.") from None

    @staticmethod
    def _documents(documents):
        if not isinstance(documents, list):
            raise ValueError
        if any(not isinstance(document, dict) or set(document) != {"id", "name", "text"}
               or any(not isinstance(value, str) for value in document.values()) for document in documents):
            raise ValueError
        return sorted(copy.deepcopy(documents), key=lambda document: (document["id"], document["name"], document["text"]))

    def validate_request(self, request):
        try:
            if not isinstance(request, dict) or request.get("prompt") != self.prompt:
                raise ValueError
            if self._documents(request.get("documents")) != self.documents:
                raise ValueError
        except (ValueError, TypeError):
            raise StudioFailure(
                "simulation_example_required",
                "Load example inputs to use judge simulation. Only the unchanged built-in prompt and documents "
                "are supported; custom sources never fall back to a live model.",
                422,
            ) from None

    def readiness(self):
        return {
            "ready": True, "model": MODEL, "mode": "simulated",
            "message": "Authored example-only simulation. No Foundry inference, credentials, or model charges. "
                       "Refinements demonstrate scripted changes, not AI reasoning.",
        }

    @staticmethod
    def _revision(previous):
        if not previous:
            return 0
        match = re.match(r"SIMULATED scripted example revision (\d+)\.", previous["analysis"]["changeSummary"])
        return int(match.group(1)) + 1 if match else 1

    def _review(self, revision):
        findings = [
            ("business", "warning", "Acknowledgement and fulfilment remain separate business states.",
             "Implement state transitions and customer-visible status; this authored graph is not application code.",
             ["example-process"]),
            ("security", "blocker", "Existing payment and warehouse callbacks have no demonstrated Entra bearer-token compatibility.",
             "Confirm existing providers can use the generated same-tenant callback authentication, or build an authenticated adapter. "
             "No provider-native webhook verification is implemented.", ["example-process"]),
            ("reliability", "warning", "Warehouse outages and duplicate callbacks require tested idempotency and recovery.",
             "Implement retry, dead-letter handling and restore tests; the workshop's 60-minute RTO and 15-minute RPO are unproven.",
             ["example-process", "example-clarifications"]),
            ("performance", "warning", "The illustrative 2,000 orders/day and 50 submissions/second burst are not measurements.",
             "Load-test acknowledgement, Blob concurrency and existing-system throttling before sizing.",
             ["example-clarifications"]),
            ("cost", "warning", "Dedicated B1 hosts, Standard messaging and storage are billable if deployed; no price is calculated.",
             "Compare current EU-region prices with the illustrative USD 1,500 planning budget, including operations.",
             ["example-clarifications"]),
            ("integration", "blocker", "The retained ERP owns stock; Blob state and queued work do not supply distributed transactions.",
             "Implement reconciliation and compensation for payment/stock races. Validate all retained HTTPS API contracts.",
             ["example-process"]),
            ("compliance", "warning", "EU residency, retention and deletion controls are not established by compilation.",
             "Choose approved EU deployment regions and obtain privacy-owner retention and deletion requirements.",
             ["example-requirements", "example-clarifications"]),
            ("operations", "warning", "Stuck-order visibility and safe operator replay require application code and runbooks.",
             "Assign fulfilment operations scoped access, correlation IDs, alerts and audited recovery procedures.",
             ["example-process", "example-clarifications"]),
            ("delivery", "warning", "The illustrative 12-week pilot is not a delivery commitment or verified implementation.",
             "Pilot one end-to-end order flow with contract tests, staged rollout and rollback.",
             ["example-clarifications"]),
        ]
        review = [{"dimension": dimension, "severity": severity,
                   "finding": "SIMULATED authored review: " + finding, "recommendation": recommendation,
                   "sourceIds": sources}
                  for dimension, severity, finding, recommendation, sources in findings]
        if revision:
            operations = next(finding for finding in review if finding["dimension"] == "operations")
            operations.update(
                finding=f"SIMULATED scripted revision {revision} adds an authored operator-controlled "
                        f"{'exception recovery' if revision % 2 else 'reconciliation'} path. "
                        "The instruction was recorded, not interpreted by AI; execution safety remains unverified.",
                recommendation="Implement authorization, idempotency and audit trails, then test the canned recovery path. "
                               "The callback compatibility and cross-system consistency blockers remain.",
                sourceIds=["example-process", "refinement"],
            )
        return review

    def _option(self, prefix, kind, revision):
        service = "AppService" if kind == "appservice" else "Functions"
        components = []

        def node(identifier, node_kind, node_service, label, responsibility, requirements, binding=None):
            value = {"id": prefix + "-" + identifier, "kind": node_kind, "service": node_service,
                     "label": label, "responsibility": responsibility, "requirementIds": requirements}
            if binding:
                value["externalDependency"] = binding
            components.append(value)

        node("storefront", "client", "Client", "Customer and operations experience",
             "Submit orders, query status and request authorized operator actions.", ["acknowledgement", "recovery"])
        node("api", kind, service, "Order API",
             "Authenticate requests, acknowledge orders and coordinate application-owned status transitions.", ["acknowledgement", "state"])
        node("state", "storage", "Storage", "Order snapshots",
             "OAuth-only Blob snapshots and application-managed idempotency; not a relational database or transaction guarantee.", ["state"])
        node("work", "servicebus", "ServiceBus", "Fulfilment work queue",
             "Buffer fulfilment while existing systems are unavailable; application retry and dead-letter handlers remain required.", ["recovery"])
        node("worker", kind, service, "Fulfilment worker",
             "Consume queued work and reconcile payment, ERP stock and warehouse dispatch through retained HTTPS APIs.", ["integrations", "recovery"])
        node("secrets", "keyvault", "KeyVault", "Integration secret references",
             "RBAC-protected secret access for existing integration credentials, without embedding credentials.", ["privacy"])
        process = next(document["text"] for document in self.documents if document["id"] == "example-process")
        declaration = next(line for line in process.splitlines()
                           if "existing integrations that must be retained" in line)
        for identifier, name, label in (
            ("erp", "ERP", "Existing ERP"), ("payment", "payment provider", "Existing payment provider"),
            ("warehouse", "warehouse", "Existing warehouse"),
        ):
            node(identifier, "external", "External HTTPS API", label,
                 "Retained integration, not a generated Azure resource. HTTPS contracts and callback compatibility require validation.",
                 ["integrations"], {"name": name, "sourceId": "example-process", "quote": declaration})
        pairs = [
            ("storefront", "api", "Submit orders and query status"),
            ("api", "state", "Write and read order snapshots"),
            ("api", "work", "Produce fulfilment work"),
            ("work", "worker", "Consume fulfilment work"),
            ("worker", "state", "Persist application-owned status"),
            ("api", "secrets", "Read integration secrets"),
            ("worker", "secrets", "Read integration secrets"),
            ("worker", "erp", "Reconcile existing stock"),
            ("worker", "payment", "Reconcile payment references"),
            ("worker", "warehouse", "Send fulfilment requests"),
            ("payment", "api", "Receive callback only through validated Entra-compatible adapter"),
            ("warehouse", "api", "Receive dispatch update only through validated Entra-compatible adapter"),
        ]
        if revision:
            queue = "exceptions" if revision % 2 else "reconciliation"
            operator = "recovery" if revision % 2 else "reconciler"
            node(queue, "servicebus", "ServiceBus", "Exception queue" if revision % 2 else "Reconciliation queue",
                 "Authored scripted holding queue; application code must explicitly route unsuccessful work here.", ["scripted-revision"])
            node(operator, "appservice", "AppService", "Human-approved recovery worker" if revision % 2 else "Operator reconciliation worker",
                 "Canned operator-controlled recovery pattern; require authenticated human approval before replay. Not implemented handlers.",
                 ["scripted-revision", "recovery"])
            pairs += [
                ("worker", queue, "Produce work requiring operator review"),
                (queue, operator, "Consume work pending authenticated human approval"),
                ("storefront", operator, "Request a scoped human-approved recovery action"),
                (operator, "work", "Produce approved replay work with application idempotency"),
                (operator, "state", "Record operator recovery decisions"),
                (operator, "secrets", "Read scoped recovery integration secrets"),
            ]
        connections = [{"id": f"{prefix}-edge-{index}", "source": prefix + "-" + source,
                        "target": prefix + "-" + target, "label": label}
                       for index, (source, target, label) in enumerate(pairs, 1)]
        return {
            "id": prefix, "name": "Web-led order orchestration" if kind == "appservice" else "Queued function workers",
            "rationale": "SIMULATED authored alternative: " + (
                "separate Linux Node 22 B1 applications own acknowledgement and durable-queue processing."
                if kind == "appservice" else
                "dedicated Linux Python 3.12/v4 B1 Function Apps separate API and queue-consumer handlers; not Consumption or Durable Functions."),
            "tradeoffs": [
                "Blob state needs application-level concurrency, reconciliation and idempotency; no distributed transaction is implied.",
                "Existing callback compatibility remains a blocker until an Entra-compatible authenticated adapter is validated.",
                "This scripted comparison is not tailored AI reasoning, executable business logic, or deployment proof.",
            ],
            "costNotes": "Dedicated B1 hosts and Standard Service Bus are billable if deployed. No sizing or live price estimate.",
            "components": components, "connections": connections,
        }

    def _analysis(self, request, previous):
        revision = self._revision(previous)
        requirements = [
            {"id": "acknowledgement", "text": "Acknowledge orders promptly and expose subsequent order status.", "sourceIds": ["prompt", "example-requirements"]},
            {"id": "state", "text": "Retain order state and payment references, not card details.", "sourceIds": ["example-process", "example-requirements"]},
            {"id": "integrations", "text": "Retain ERP stock ownership, payment provider and warehouse integrations.", "sourceIds": ["example-process"]},
            {"id": "privacy", "text": "Keep customer data in approved EU regions and provide scoped operational access.", "sourceIds": ["example-requirements", "example-clarifications"]},
            {"id": "recovery", "text": "Accept orders during warehouse outages and support controlled stuck-order recovery.", "sourceIds": ["example-process", "example-clarifications"]},
            {"id": "planning", "text": "Validate illustrative workload, recovery, budget and delivery assumptions before deployment.", "sourceIds": ["example-clarifications"]},
        ]
        if revision:
            requirements.append({
                "id": "scripted-revision",
                "text": f"Demonstrate canned revision {revision}: an operator-controlled "
                        f"{'exception recovery' if revision % 2 else 'reconciliation'} path. "
                        "The instruction is recorded for demonstration, not semantically executed by AI.",
                "sourceIds": ["refinement", "example-process"],
            })
        return {
            "title": "SIMULATED example: order-to-fulfilment",
            "summary": "Authored judge demonstration for the exact Load Example sources. Two scripted alternatives; "
                       "no model inference, no arbitrary instruction interpretation, no application deployment.",
            "businessProcess": ["Acknowledge the order and retain its status.", "Queue fulfilment work while dependencies are unavailable.",
                                "Reconcile retained payment, ERP stock and warehouse dispatch.", "Expose status and controlled operator recovery."],
            "requirements": requirements,
            "assumptions": [
                "The demonstration assumes existing integrations expose HTTPS APIs; contracts and Entra callback compatibility are unverified.",
                "All runtime handlers, identity checks, idempotency, compensation and recovery runbooks require implementation.",
                "Workshop workload, RTO/RPO, budget and pilot date are illustrative inputs, not measured or approved targets.",
            ],
            "questions": [],
            "options": [self._option("web", "appservice", revision), self._option("events", "functions", revision)],
            "recommendedOptionId": previous["analysis"]["recommendedOptionId"] if previous and previous["analysis"]["recommendedOptionId"] in {"web", "events"} else "events",
            "review": self._review(revision),
            "changeSummary": f"SIMULATED scripted example revision {revision}. "
                             + ("Initial authored baseline; no model was called." if revision == 0 else
                                f"Canned {'exception recovery' if revision % 2 else 'operator reconciliation'} improvement. "
                                "User instruction recorded, not AI reasoning or a semantic implementation of arbitrary direction. "
                                "Callback compatibility and distributed-consistency blockers remain."),
        }

    async def generate(self, role, request, analysis=None, previous=None, progress=None):
        self.validate_request(request)
        if role not in {"synthesis", "assurance"}:
            raise StudioFailure("invalid_role", "Unsupported simulation operation.")
        if progress:
            progress("SIMULATED: preparing the authored example " + role + " output; no model call.")
        value = self._analysis(request, previous) if role == "synthesis" else {"review": self._review(self._revision(previous))}
        return value, {"role": role, "model": MODEL, "origin": self.origin,
                       "responseId": f"sim_{role}_" + secrets.token_hex(16), "durationMs": 0}
